sudo: required

services:
- docker

language:

git:
  depth: 3

install:

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull oxyl/grpc-lb:yourlanguage
- docker build -t oxyl/grpc-lb:yourlanguage .
- docker push oxyl/grpc-lb:yourlanguage
