sudo: required

services:
- docker

language: node_js
node_js:
- "10.12.0"
cache: npm

git:
  depth: 3

install:
- npm install

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker pull oxyl/grpc-lb:test
- docker build -t oxyl/grpc-lb:test .
- docker push oxyl/grpc-lb:test
