apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  # Use port named "grpclb" to expose the needed DNS SRV record
  - name: grpclb
    port: 9000
  selector:
    app: client
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: server
        image: oxyl/grpc-lb:test
        ports:
        - containerPort: 9000
        env:
        - name: RPC_PORT
          value: "9000"
        - name: RPC_HOST
          value: "server.default.svc.cluster.local"
