apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  clusterIP: None  # Headless service
  ports:
  # Use port named "grpclb" to expose the needed DNS SRV record
  - name: grpclb
    port: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: oxyl/grpc-lb:test
        metadata:
          labels:
            app: server
        ports:
        - containerPort: 9000
        env:
        - name: RPC_PORT
          value: 9000
        - name: RPC_TYPE
          value: "server"

