apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  clusterIP: None  # Headless service
  ports:
  # Use port named "grpclb" to expose the needed DNS SRV record
  - name: grpclb
    port: 9000
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: oxyl/grpc-lb:test
        ports:
        - containerPort: 9000
        env:
        - name: RPC_PORT
          value: "9000"
        - name: RPC_TYPE
          value: "server"

